### ISSUE TITLE
Informative error message when amplitude files missing

### ISSUE THREAD

**Issue by seaaan** [daattali/ddpcr#10]
I periodically forget to export the `*_Amplitude.csv` files before trying to read in the data in R. The error message that results is: `Error in basename(.) : a character vector argument expected`. It would be cool if you could detect that there weren't any files and give me a reminder in the error message. 

Thanks for writing this package. We use ddPCR a fair amount in my lab and this package has helped me start to transition away from QuantaSoft! If you ever want feedback/user testing or to collaborate, I'd be interested.

**Comment by daattali** [comment]
You're right, that's a terribly useless error message! I will fix that next
week (away at conference right now). I'd love to hear about your use of the
tool and how you find it, and potentially share some of your data or
results so I can see how it does, if you can?
Also,  would you mind telling me how you found out about this package? I
haven't advertised it at all yet so it's very exciting to get a few users
(you're the third to email me this week!)

Thanks for the report!

**Comment by daattali** [comment]
@seaaan Just to clarify: you're getting this error when using the command line, but not when using the shiny (GUI) app, right?  Because in the shiny app I do have a good error message

**Comment by seaaan** [comment]
Yep, I got the error when using R through the command line (okay R Studio). I just installed the updated version and I got the better error message as expected, so thanks! 

To answer your other questions: 
So far, I have mainly used it for convenient loading of ddPCR files into R and I haven't used the analysis portions of the package very much. Right now we're working on an assay to detect 3 HIV genes in one well (similar to http://www.ncbi.nlm.nih.gov/pubmed/25277746), so the classical --/+-/++/-+ classification of droplets isn't what we need. Here's an example:
![droplets-subsampled](https://cloud.githubusercontent.com/assets/10538357/16592627/798f6cc4-4296-11e6-928a-e2e414b43c33.png)

In general we use ddPCR for gene expression measurements so we typically just use QuantaSoft to set thresholds and get count data, but it would be great to move this to R. I'd be happy to share some data with you. What would be helpful?

I found the package by googling for R and ddPCR. It doesn't necessarily make sense to continue this conversation in this closed issue, so you can email me. It's smhughes at the domain fredhutch.org.

**Comment by daattali** [comment]
Thanks for the info
