### ISSUE TITLE
Calling select() with NA in a column name

### ISSUE THREAD

**Issue by krlmlr** [daattali/ddpcr#22]
gives an error in the dplyr 0.7.5 release candidate. To replicate:

```r
library(ddpcr)
plate <- new_plate(sample_data_dir(), type = plate_types$custom_thresholds)
plate %>% reset(keep_type = TRUE)
```

https://github.com/tidyverse/dplyr/blob/master/revdep/new-problems.md#ddpcr

**Comment by daattali** [comment]
@krlmlr Approx when is this version scheduled for release?

**Comment by krlmlr** [comment]
End of March ;-)

I'd like to push to CRAN as soon as possible. Usually, CRAN accepts the submission as long as we've notified all maintainers of packages we break, and it takes a few days/weeks until the update is accepted.

**Comment by daattali** [comment]
I believe this is a dplyr bug https://github.com/tidyverse/dplyr/issues/3603
