### ISSUE TITLE
warning message

### ISSUE THREAD

**Issue by jyin3dmont0n** [daattali/ddpcr#26]
when calling merge_dfs_overwrite_col(), the following messages were received in console:
Warning messages:
1: `select_()` was deprecated in dplyr 0.7.0.
ℹ Please use `select()` instead.
ℹ The deprecated feature was likely used in the ddpcr package.
  Please report the issue at <https://github.com/daattali/ddpcr/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
2: `rename_()` was deprecated in dplyr 0.7.0.
ℹ Please use `rename()` instead.
ℹ The deprecated feature was likely used in the ddpcr package.
  Please report the issue at <https://github.com/daattali/ddpcr/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by daattali** [comment]
Thanks. This is known, and unless they become unfunctional, they will remain , since this package is mostly in maintenance mode and not active development. Only fatal errors will be fixed.
https://github.com/daattali/ddpcr/issues/25

**Comment by paulduf** [comment]
Hello, is there a reason why not simply replacing these with the proper ones ? I can submit a PR if it helps.

**Comment by daattali** [comment]
A PR would be welcomed
