### ISSUE TITLE
Must we really download then upload the sample data in the app?

### ISSUE THREAD

**Issue by jennybc** [daattali/ddpcr#9]
I have no idea if this messes with other elegant things you've done.

But it would be nice to just say "use sample data" instead of downloading the single csv, then finding it, then re-uploading it into your app. Like a demo mode. And have more than 1 well. Maybe 4?

**Comment by daattali** [comment]
You can use the 'Use sample data' tab. The "download sample file" is more to show you what the file in case you're not sure.  Does this answer your question?

**Comment by jennybc** [comment]
OK I see. Not sure what to make of the fact that I didn't find that tab. Is it me or is it you? 😂 But YES that's exactly what I meant.
